# Generated by Django 3.1.4 on 2021-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210106_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='last_page',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
